NAME  : PARVATHY KRISHNAN
REG NO: CHN18CS095


AGGREGATE FUNCTIONS IN SQL

-------------------------------
a) CREATING A TABLE 

CREATE TABLE EMPLOYEE
    (CODE VARCHAR(5) PRIMARY KEY,
     NAME VARCHAR(20) NOT NULL,
     DOB DATE ,
     DESIGNATION VARCHAR(25),
     SALARY DECIMAL(12.2));
-----------------------------------

b) INSERTING VALUES

INSERT INTO EMPLOYEE VALUES
   ("A1","JULIA","1990-05-05","MANAGER",60000.00),
   ("A2","JORDAN","2000-10-15","CLERK",30000.00),
   ("A3","HARRIS","1996-07-08","CASHIER",28000.00),
   ("A4","STEPHY","1988-06-09","CLERK",35000.00);
-----------------------------------

c) SUM OF SALARY FROM TABLE WITH DESIGNATION AS CLERK

SELECT SUM(SALARY) FROM EMPLOYEE WHERE DESIGNATION="CLERK";
------------------------------------

d) MAXIMUM SALARY VALUE FROM TABLE

SELECT MAX(SALARY) FROM EMPLOYEE;
------------------------------------

e) AVERAGE OF SALARY OF EMPLOYEES

SELECT AVG(SALARY) FROM EMPLOYEE;
------------------------------------

f) MINIMUM SALARY VALUE FROM TABLE

SELECT MIN(SALARY) FROM TABLE;
------------------------------------

g) TOTAL NUMBER OF EMPLOYEES

SELECT COUNT(*) FROM EMPLOYEE;
----------------------------------
