NAME  : PARVATHY KRISHNAN
REG NO: CHN18CS095


SHOW DATABASES;

USE COLLEGE;


CREATE TABLE DEPT1(
 code VARCHAR(30) PRIMARY KEY ,
 title VARCHAR(30) NOT NULL, 
 Dept_name VARCHAR(30) UNIQUE,
 Dept_id INT,
 Salary INT CHECK(Salary>2000)
 );


INSERT INTO DEPT1 
VALUES ('D1','ACCOUNTANT','SALES',1,50000),('D2','CASHIER','FINANCE',2,30000),('D3','MANAGER','TAX',3,70000);

SELECT * FROM DEPT1;


CREATE TABLE INSTRUCTOR1(
NAME VARCHAR(20) NOT NULL,
CODE VARCHAR(10),
ID INT PRIMARY KEY DEFAULT 0
);

INSERT INTO INSTRUCTOR1
VALUES ('JUAN','I1',1),('MICHAEL','I2',2),('HABES','I3',3);

SELECT * FROM INSTRUCTOR1;



INSERT INTO INSTRUCTOR1(NAME,CODE)
VALUES('BHAVYA','I4');

SELECT * FROM INSTRUCTOR1;

 
