NAME  :  PARVATHY KRISHNAN
REG NO:  CHN18CS095

#a
CREATE TABLE STORE(
    ORDER_NO INT PRIMARY KEY ,
    CODE VARCHAR(20) ,
    ITEM VARCHAR(30) NOT NULL,
    QUANTITY INT NOT NULL,
    PRICE DECIMAL(10,2) ,
    DISCOUNT DECIMAL(2,2) ,
    MRP DECIMAL(10,2) NOT NULL
);


#b
INSERT INTO STORE VALUES (1, "BH", "BRUSH", 2,15,0,15),
(2,"PST", "PASTE", 1,20,0,20),
(3,"BUK","BOOK",2,25,0,25);

#c
SELECT * FROM Store;


#d
CREATE VIEW DETAILS AS
SELECT ITEM , QUANTITY FROM STORE;

#e
INSERT INTO STORE VALUES 
(4,"SP","SOAP",10,50,0,50),
(5,"PNCL","PENCIL",5,40,0,40);

#f
SELECT * FROM DETAILS;

#g
DROP VIEW DETAILS;


